---
title: "Getting Started"
author: "Sarah Gaichas"
date: "`r Sys.Date()`"
output: 
  html_document:
    mathjax: local
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Overview

This application summarizes ecosystem indicator data potentially relevant to the Mid-Atlantic Council. The purpose of this application is to help identify indicators with qualities relevant to a particular application.

Indicators are described and evaluated for SMART attributes; to what extent indicators are:

* **Specific**: clearly defined, describing exactly what is measured at what scale and how the indicator is calculated so that methods can be repeated. In the next phase, the indicator can be directly linked to a management process objective. 
* **Measurable**: appropriate quantitative or qualitative data are available to evaluate change over time. Tied to measurable management process objective. 
* **Achievable**: responses to changes in management are detectable within the management time frame--objectives tied to the indicator must be achievable. 
* **Relevant**: accurately reflects changes in the underlying process of concern. In the next phase, the indicator can be directly linked to a management process objective. 
* **Time-bound**: how often is indicator measured and does this align with the process of concern, and later, the management process
within a SMART framework: are the indicators Specific, Measurable, Achievable, Relevant, and Timely for the priority Council decisions? 

## How to use the application

Select a SMART level for indicators in the left panel to see how many meet that threshold above. They are highlighted in green in the table. The figure gives a count of indicators by category. 

The Category page gives more details on indicators within your chosen category. 

On the other pages, dive into particular attributes.

Do you need annual indicators for a routine management application? Filter indicators to see which ones are updated annually on the Timing page.

Do you need indicators for a particular area at a certain scale? Filter indicators to see which cover your EPU or area on the Spatial page.

Do you have a particular management decision in mind? Filter indicators by potential linkages to management on the Management page.

Links to source information for particular indicators are given on the Details page.

